//  namespace that acts as a container for related interfaces and declarations
module HelloApp
{
  // These lines declare the interface statement
  interface Hello
  {
    // This line is an operation statement.
    string sayHello();
	// This line is another
    oneway void shutdown();
  };
};