package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, June 6, 2014 4:47:15 PM ICT
*/


// These lines declare the interface statement
public interface HelloOperations 
{

  // This line is an operation statement.
  String sayHello ();

  // This line is another
  void shutdown ();
} // interface HelloOperations
