package EchoApp;


/**
* EchoApp/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* Saturday, June 14, 2014 1:41:28 PM ICT
*/

public interface EchoOperations 
{

  // This line is an operation statement.
  String doEcho (String str);

  // This line is another
  void shutdown ();
} // interface EchoOperations
