package EchoApp;


/**
* EchoApp/Echo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* Saturday, June 14, 2014 1:41:28 PM ICT
*/

public interface Echo extends EchoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Echo
