package EchoApp;


/**
* EchoApp/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* Friday, June 6, 2014 6:49:20 PM ICT
*/

public interface EchoOperations 
{

  // This line is an operation statement.
  String echo (String str);

  // This line is another
  void shutdown ();
} // interface EchoOperations
